-- ****** Object: Constraint CS414S16.TEST_TAKEN_ENROLLMENT_FK Script Date: 2/16/2016 5:30:24 PM ******
ALTER TABLE "TEST_TAKEN" ADD CONSTRAINT "TEST_TAKEN_ENROLLMENT_FK" FOREIGN KEY ("ENROLLMENT_ID") REFERENCES "ENROLLMENT"("ENROLLMENT_ID") ENABLE;
