-- ****** Object: Table CS414S16.CLASS Script Date: 2/16/2016 5:30:24 PM ******
  CREATE TABLE "CLASS" 
   (	"CLASS_ID" NUMBER NOT NULL ENABLE,
	"CODE" VARCHAR2(6) NOT NULL ENABLE,
	"TITLE" VARCHAR2(30) NOT NULL ENABLE,
	CONSTRAINT "CLASS_PK" PRIMARY KEY ("CLASS_ID") ENABLE
   );