-- ****** Object: Constraint CS414S16.SECTION_TEACHER_FK Script Date: 2/16/2016 5:30:24 PM ******
ALTER TABLE "SECTION" ADD CONSTRAINT "SECTION_TEACHER_FK" FOREIGN KEY ("TEACHER_ID") REFERENCES "END_USER"("USER_ID") ON DELETE SET NULL ENABLE;
