-- ****** Object: Table CS414S16.MULTPILE_CHOICE_CHOICE Script Date: 2/16/2016 5:30:24 PM ******
  CREATE TABLE "MULTPILE_CHOICE_CHOICE" 
   (	"MULTIPLE_CHOICE_CHOICE_ID" NUMBER NOT NULL ENABLE,
	"QUESTION_ID" NUMBER NOT NULL ENABLE,
	"CHOICE_TEXT" VARCHAR2(100) NOT NULL ENABLE,
	"SET_ORDER" NUMBER NOT NULL ENABLE,
	CONSTRAINT "MULTPILE_CHOICE_CHOICE_PK" PRIMARY KEY ("MULTIPLE_CHOICE_CHOICE_ID") ENABLE,
	CONSTRAINT "MULTPILE_CHOICE_CHOICE_UK" UNIQUE ("QUESTION_ID","SET_ORDER") ENABLE
   );