-- ****** Object: Constraint CS414S16.TEST_SECTION_FK Script Date: 2/16/2016 5:30:24 PM ******
ALTER TABLE "TEST" ADD CONSTRAINT "TEST_SECTION_FK" FOREIGN KEY ("SECTION_ID") REFERENCES "SECTION"("SECTION_ID") ENABLE;
