-- ****** Object: Constraint CS414S16.SECTION_CLASS_FK Script Date: 2/16/2016 5:30:24 PM ******
ALTER TABLE "SECTION" ADD CONSTRAINT "SECTION_CLASS_FK" FOREIGN KEY ("CLASS_ID") REFERENCES "CLASS"("CLASS_ID") ENABLE;
