-- ****** Object: Constraint CS414S16.ENROLLMENT_STUDENT_FK Script Date: 2/16/2016 5:30:24 PM ******
ALTER TABLE "ENROLLMENT" ADD CONSTRAINT "ENROLLMENT_STUDENT_FK" FOREIGN KEY ("STUDENT_ID") REFERENCES "END_USER"("USER_ID") ON DELETE SET NULL ENABLE;
