-- ****** Object: Constraint CS414S16.QUESTION_TEST_FK Script Date: 2/16/2016 5:30:24 PM ******
ALTER TABLE "QUESTION" ADD CONSTRAINT "QUESTION_TEST_FK" FOREIGN KEY ("TEST_ID") REFERENCES "TEST"("TEST_ID") ENABLE;
