-- ****** Object: Table CS414S16.TRUE_FALSE Script Date: 2/16/2016 5:30:24 PM ******
  CREATE TABLE "TRUE_FALSE" 
   (	"QUESTION_ID" NUMBER NOT NULL ENABLE,
	"QUESTION_TEXT" VARCHAR2(100) NOT NULL ENABLE,
	"ANSWER" VARCHAR2(1) NOT NULL ENABLE,
	CONSTRAINT "TRUE_FALSE_ANSWER_CHK" CHECK (ANSWER = 'T' OR ANSWER = 'F') ENABLE
   );