-- ****** Object: Table CS414S16.MATCHING_BODY Script Date: 2/16/2016 5:30:24 PM ******
  CREATE TABLE "MATCHING_BODY" 
   (	"QUESTION_ID" NUMBER NOT NULL ENABLE,
	"QUESTION_TEXT" VARCHAR2(200) NOT NULL ENABLE,
	"ANSWER" VARCHAR2(200) NOT NULL ENABLE
   );