-- ****** Object: Table CS414S16.END_USER Script Date: 2/16/2016 5:30:24 PM ******
  CREATE TABLE "END_USER" 
   (	"USER_ID" NUMBER NOT NULL ENABLE,
	"F_NAME" VARCHAR2(25) NOT NULL ENABLE,
	"L_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"PERMISSION_LEVEL" VARCHAR2(1) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(50) NOT NULL ENABLE,
	"PASSWORD" VARCHAR2(50) NOT NULL ENABLE,
	CONSTRAINT "END_USER_CHK1" CHECK (PERMISSION_LEVEL = 'A' OR PERMISSION_LEVEL = 'T' OR PERMISSION_LEVEL = 'S') ENABLE,
	CONSTRAINT "END_USER_PK" PRIMARY KEY ("USER_ID") ENABLE
   );