-- ****** Object: Table CS414S16.ENROLLMENT Script Date: 2/16/2016 5:30:24 PM ******
  CREATE TABLE "ENROLLMENT" 
   (	"ENROLLMENT_ID" NUMBER NOT NULL ENABLE,
	"STUDENT_ID" NUMBER NOT NULL ENABLE,
	"SECTION_ID" NUMBER NOT NULL ENABLE,
	CONSTRAINT "ENROLLMENT_PK" PRIMARY KEY ("ENROLLMENT_ID") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS
 ;