-- ****** Object: Constraint CS414S16.MULTPILE_CHOICE_CHOICE_QU_FK Script Date: 2/16/2016 5:30:24 PM ******
ALTER TABLE "MULTPILE_CHOICE_CHOICE" ADD CONSTRAINT "MULTPILE_CHOICE_CHOICE_QU_FK" FOREIGN KEY ("QUESTION_ID") REFERENCES "QUESTION"("QUESTION_ID") ENABLE;
