-- ****** Object: Constraint CS414S16.TEST_TAKEN_TEST_FK Script Date: 2/16/2016 5:30:24 PM ******
ALTER TABLE "TEST_TAKEN" ADD CONSTRAINT "TEST_TAKEN_TEST_FK" FOREIGN KEY ("TEST_ID") REFERENCES "TEST"("TEST_ID") ENABLE;
