-- ****** Object: Constraint CS414S16.ENROLLMENT_SECTION_FK Script Date: 2/16/2016 5:30:24 PM ******
ALTER TABLE "ENROLLMENT" ADD CONSTRAINT "ENROLLMENT_SECTION_FK" FOREIGN KEY ("SECTION_ID") REFERENCES "SECTION"("SECTION_ID") ON DELETE SET NULL ENABLE;
