-- ****** Object: Table CS414S16.SECTION Script Date: 2/16/2016 5:30:24 PM ******
  CREATE TABLE "SECTION" 
   (	"SECTION_ID" NUMBER NOT NULL ENABLE,
	"TEACHER_ID" NUMBER NOT NULL ENABLE,
	"CLASS_ID" NUMBER NOT NULL ENABLE,
	"SEMESTER" VARCHAR2(12) NOT NULL ENABLE,
	CONSTRAINT "SECTION_PK" PRIMARY KEY ("SECTION_ID") ENABLE
   );