-- ****** Object: Table CS414S16.TEST Script Date: 2/16/2016 5:30:24 PM ******
  CREATE TABLE "TEST" 
   (	"TEST_ID" NUMBER NOT NULL ENABLE,
	"SECTION_ID" NUMBER NOT NULL ENABLE,
	"TITLE" VARCHAR2(50) NOT NULL ENABLE,
	"DUE_DATE" DATE NOT NULL ENABLE,
	"TIME_LIMIT" NUMBER NOT NULL ENABLE,
	"POSSIBLE_POINTS" NUMBER,
	CONSTRAINT "TEST_PK" PRIMARY KEY ("TEST_ID") ENABLE
   );