-- ****** Object: Constraint CS414S16.MATCHING_BODY_FK1 Script Date: 2/16/2016 5:30:24 PM ******
ALTER TABLE "MATCHING_BODY" ADD CONSTRAINT "MATCHING_BODY_FK1" FOREIGN KEY ("QUESTION_ID") REFERENCES "QUESTION"("QUESTION_ID") ENABLE;
