-- ****** Object: Table CS414S16.MULTIPLE_CHOICE Script Date: 2/16/2016 5:30:24 PM ******
  CREATE TABLE "MULTIPLE_CHOICE" 
   (	"QUESTION_ID" NUMBER NOT NULL ENABLE,
	"QUESTION_TEXT" VARCHAR2(200) NOT NULL ENABLE,
	"CHOICE_ID" NUMBER NOT NULL ENABLE
   );