-- Drop the existing table (if any)

DROP TABLE "CS414S16"."END_USER" 

-- Create a new Relational table with 3 columns

--------------------------------------------------------
--  DDL for Table END_USER
--------------------------------------------------------

  CREATE TABLE "CS414S16"."END_USER" 
   (	"USER_ID" NUMBER, 
	"F_NAME" VARCHAR2(25 BYTE), 
	"L_NAME" VARCHAR2(30 BYTE), 
	"PERMISSION_LEVEL" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index END_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CS414S16"."END_USER_PK" ON "CS414S16"."END_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table END_USER
--------------------------------------------------------

  ALTER TABLE "CS414S16"."END_USER" ADD CONSTRAINT "END_USER_CHK1" CHECK (PERMISSION_LEVEL = 'A' OR PERMISSION_LEVEL = 'T' OR PERMISSION_LEVEL = 'S') ENABLE;
  ALTER TABLE "CS414S16"."END_USER" ADD CONSTRAINT "END_USER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CS414S16"."END_USER" MODIFY ("PERMISSION_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "CS414S16"."END_USER" MODIFY ("L_NAME" NOT NULL ENABLE);
  ALTER TABLE "CS414S16"."END_USER" MODIFY ("F_NAME" NOT NULL ENABLE);
  ALTER TABLE "CS414S16"."END_USER" MODIFY ("USER_ID" NOT NULL ENABLE);

