-- Drop the existing table (if any)

DROP TABLE "CS414S16"."MULTIPLE_CHOICE";

-- Create a new Relational table with 3 columns

--------------------------------------------------------
--  DDL for Table MULTIPLE_CHOICE
--------------------------------------------------------

  CREATE TABLE "CS414S16"."MULTIPLE_CHOICE" 
   (	"QUESTION_ID" NUMBER, 
	"QUESTION_TEXT" VARCHAR2(200 BYTE), 
	"CHOICE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MULTIPLE_CHOICE
--------------------------------------------------------

  ALTER TABLE "CS414S16"."MULTIPLE_CHOICE" MODIFY ("CHOICE_ID" NOT NULL ENABLE);
  ALTER TABLE "CS414S16"."MULTIPLE_CHOICE" MODIFY ("QUESTION_TEXT" NOT NULL ENABLE);
  ALTER TABLE "CS414S16"."MULTIPLE_CHOICE" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MULTIPLE_CHOICE
--------------------------------------------------------

  ALTER TABLE "CS414S16"."MULTIPLE_CHOICE" ADD CONSTRAINT "MULTIPLE_CHOICE_CHOICE_FK" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "CS414S16"."MULTPILE_CHOICE_CHOICE" ("MULTIPLE_CHOICE_CHOICE_ID") ENABLE;
  ALTER TABLE "CS414S16"."MULTIPLE_CHOICE" ADD CONSTRAINT "MULTIPLE_CHOICE_QUESTION_FK" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "CS414S16"."QUESTION" ("QUESTION_ID") ENABLE;
