-- Drop the existing table (if any)

DROP TABLE "CS414S16"."TEST";

--------------------------------------------------------
--  DDL for Table TEST
--------------------------------------------------------

  CREATE TABLE "CS414S16"."TEST" 
   (	"TEST_ID" NUMBER, 
	"SECTION_ID" NUMBER, 
	"TITLE" VARCHAR2(50 BYTE), 
	"DUE_DATE" DATE, 
	"TIME_LIMIT" NUMBER, 
	"POSSIBLE_POINTS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CS414S16"."TEST_PK" ON "CS414S16"."TEST" ("TEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TEST
--------------------------------------------------------

  ALTER TABLE "CS414S16"."TEST" ADD CONSTRAINT "TEST_PK" PRIMARY KEY ("TEST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CS414S16"."TEST" MODIFY ("TIME_LIMIT" NOT NULL ENABLE);
  ALTER TABLE "CS414S16"."TEST" MODIFY ("DUE_DATE" NOT NULL ENABLE);
  ALTER TABLE "CS414S16"."TEST" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "CS414S16"."TEST" MODIFY ("SECTION_ID" NOT NULL ENABLE);
  ALTER TABLE "CS414S16"."TEST" MODIFY ("TEST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TEST
--------------------------------------------------------

  ALTER TABLE "CS414S16"."TEST" ADD CONSTRAINT "TEST_SECTION_FK" FOREIGN KEY ("SECTION_ID")
	  REFERENCES "CS414S16"."SECTION" ("SECTION_ID") ENABLE;
